# Generated by Django 2.1 on 2019-07-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('email', models.TextField(max_length=128)),
                ('registerdate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
